define([], function () {
  return {
      "PropertyPaneDescription": "Search Web Part Settings",
      "QueryGroupName": "Search query settings",
      "TemplateGroupName": "Template settings",
      "TitleFieldLabel": "Web part title",
      "QueryFieldLabel": "Specify your search query",
      "QueryFieldDescription": "You can make use of following tokens: {Site} - {SiteCollection} - {Today} or {Today+NR} or {Today-NR} - {CurrentDisplayLanguage} - {User}, {User.Name}, {User.Email}",
      "FieldsMaxResults": "Number of results to render",
      "SortingFieldLabel": "Sorting (MP:ascending or descending) - example: lastmodifiedtime:ascending,author:descending",
      "DebugFieldLabel": "Show debug output?",
      "DebugFieldLabelOn": "Yes",
      "DebugFieldLabelOff": "No",
      "ExternalFieldLabel": "Specify the external template URL",
      "ScriptloadingFieldLabel": "Enable script loading from the template?",
      "ScriptloadingFieldLabelOn": "Danger mode",
      "ScriptloadingFieldLabelOff": "Safe mode",
      "DuplicatesFieldLabel": "Trim duplicate results?",
      "DuplicatesFieldLabelOn": "Yes",
      "DuplicatesFieldLabelOff": "No",
      "PrivateGroupsFieldLabel": "Search through content of private groups?",
      "PrivateGroupsFieldLabelOn": "Yes",
      "PrivateGroupsFieldLabelOff": "No, only public groups",
      "ResultTypeLabel": "Show projects or documents?",

      "QuertValidationEmpty": "Please specify a search query",
      "TemplateValidationEmpty": "Please specify the URL of your template",
      "TemplateValidationHTML": "Please use an HTML file for the template",

      "ScriptsDialogHeader": "Script tags found in your template",
      "ScriptsDialogSubText": "If you want to be able to run the scripts from your template, you have to activate the script loading option.",

      "ResultTypeProject": "Projects",
      "ResultTypeDocument": "Documents",

      "lengthMenu": 'Show _MENU_ items',
      "lengthMenuDocs": 'Show _MENU_ items',
      "search": 'Filter:',
      "info": 'Showing _START_ to _END_ of _TOTAL_ items',
      "emptyTable": 'No items found',
      "zeroRecords":    "No items match this filter",
      "infoFiltered":   "(filtered from _MAX_ items)",
      "first":'First',
      "last": 'Last',
      "next": 'Next',
      "previous": 'Previous',
      "titleColumn": 'Title',
      "projectIdColumn": 'Project ID',
      "projectStartColumn": 'Start',
      "projectOwnerColumn": 'Project owner',
      "modifiedColumn": 'Modified',
      "modifiedByColumn": 'Modified by',
      "infoEmpty": "Showing 0 to 0 of 0 entries",

      "loadingMessage":  'Loading items',
      "errorMessage":  'An error occurred',
      "showErrorMessage":  'Show the error message',
      "hideErrorMessage":  'Hide the error message'
  }
});
